/*
Copyright (c) 2013 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module dmech.geometry;

import std.math;

import dlib.math.vector;
import dlib.math.matrix3x3;
import dlib.math.matrix4x4;
import dlib.math.utils;
import dlib.geometry.aabb;
import dlib.geometry.sphere;

enum GeomType
{
    Undefined,
    Sphere,
    Box,
    Cylinder,
    Cone,
    Ellipsoid,
    Triangle
}

abstract class Geometry
{
    GeomType type = GeomType.Undefined;
    Matrix4x4f transformation;

    this()
    {
        transformation = identityMatrix4x4f();
    }
    
    @property Vector3f position()
    {
        return transformation.translation;
    }
    
    Vector3f supportPoint(Vector3f dir)
    {
        return Vector3f(0.0f, 0.0f, 0.0f);
    }
    
    float inertiaMoment(float mass)
    {
        return mass;
    }

    @property Sphere boundingSphere()
    {
        return Sphere(position, 1.0f);
    }
}

class GeomSphere: Geometry
{
    float radius;
    
    this(float r)
    {
        super();
        type = GeomType.Sphere;
        radius = r;
    }

    override Vector3f supportPoint(Vector3f dir)
    {
        return dir.normalized * radius;
    }
    
    override float inertiaMoment(float mass)
    {
        return 2.0f / 5.0f * mass * radius * radius;
    }

    override @property Sphere boundingSphere()
    {
        return Sphere(position, radius);
    }
}

class GeomBox: Geometry
{
    Vector3f halfSize;

    this(Vector3f hsize)
    {
        super();
        type = GeomType.Box;
        halfSize = hsize;
    }

    override Vector3f supportPoint(Vector3f dir)
    {
        Vector3f result;
        result.x = sign(dir.x) * halfSize.x;
        result.y = sign(dir.y) * halfSize.y;
        result.z = sign(dir.z) * halfSize.z;
        return result;
    }

    override @property Sphere boundingSphere()
    {
        return Sphere(position, halfSize.length);
    }
}

class GeomCylinder: Geometry
{
    float height;
    float radius;
    
    this(float h, float r)
    {
        super();
        type = GeomType.Cylinder;
        height = h;
        radius = r;
    }

    override Vector3f supportPoint(Vector3f dir)
    {
        Vector3f result;
        float sigma = sqrt((dir.x * dir.x + dir.z * dir.z));

        if (sigma > 0.0f)
        {
            result.x = dir.x / sigma * radius;
            result.y = sign(dir.y) * height * 0.5f;
            result.z = dir.z / sigma * radius;
        }
        else
        {
            result.x = 0.0f;
            result.y = sign(dir.y) * height * 0.5f;
            result.z = 0.0f;
        }
        
        return result;
    }

    // TODO: boundingSphere
}

class GeomCone: Geometry
{
    float radius;
    float height;

    this(float h, float r)
    {
        super();
        type = GeomType.Cone;
        height = h;
        radius = r;
    }

    override Vector3f supportPoint(Vector3f dir)
    {
        float zdist = dir[0] * dir[0] + dir[1] * dir[1];
        float len = zdist + dir[2] * dir[2];
        zdist = sqrt(zdist);
        len = sqrt(len);
        float half_h = height * 0.5;
        float radius = radius;

        float sin_a = radius / sqrt(radius * radius + 4.0f * half_h * half_h);

        if (dir[2] > len * sin_a)
            return Vector3f(0.0f, 0.0f, half_h);
        else if (zdist > 0.0f)
        {
            float rad = radius / zdist;
            return Vector3f(rad * dir[0], rad * dir[1], -half_h);
        }
        else
            return Vector3f(0.0f, 0.0f, -half_h);
    }

    // TODO: boundingSphere
}

class GeomEllipsoid: Geometry
{
    Vector3f radii;

    this(Vector3f r)
    {
        super();
        type = GeomType.Ellipsoid;
        radii = r;
    }

    override Vector3f supportPoint(Vector3f dir)
    {
        return dir.normalized * radii;
    }

    // TODO: boundingSphere
}
