/*
Copyright (c) 2013 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module dmech.hashtable;

class HashTable(T)
{
    struct Entry(T)
    {
        ulong key;
        T value;
        bool valid = false;
    }

    const uint size;
    Entry!(T)[] table;

    this(uint size)
    {
        this.size = size;
        table = new Entry!(T)[size];
    }

    T* get(ulong key)
    {
        uint hash = (key % size);

        while (table[hash].valid && table[hash].key != key)
            hash = (hash + 1) % size;

        if (!table[hash].valid)
            return null;
        else
            return &table[hash].value;
    }

    void set(ulong key, T value)
    {
        uint hash = (key % size);

        while (table[hash].valid && table[hash].key != key)
            hash = (hash + 1) % size;

        table[hash] = Entry!(T)(key, value, true);
    } 

    void remove(ulong key)
    {
        uint hash = (key % size);

        while (table[hash].valid && table[hash].key != key)
            hash = (hash + 1) % size;

        table[hash].valid = false;
    }

    int opApply(int delegate(ref T) func)
    {
        int result = 0;

        foreach(ref entry; table)
        {
            if (entry.valid)
            {
                //auto val = &entry.value;
                result = func(entry.value);
                if (result)
                    break;
            }
        }

        return result;
    }
}

ulong szudzikPair(uint a, uint b)
{
    return a >= b ? a * a + a + b : a + b * b;
}

class PairHashTable(T): HashTable!(T)
{
    this(uint size)
    {
        super(size);
    }

    T* get(uint k1, uint k2)
    {
        return super.get(szudzikPair(k1, k2));
    }

    void set(uint k1, uint k2, T value)
    {
        super.set(szudzikPair(k1, k2), value);
    }

    void remove(uint k1, uint k2)
    {
        super.remove(szudzikPair(k1, k2));
    }
}

