/*
Copyright (c) 2013 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module dmech.manifold;

import std.math;
import std.stdio;
import core.exception;

import dlib.math.vector;
import dlib.math.matrix4x4;
import dlib.math.quaternion;
import dlib.math.utils;
import dlib.geometry.plane;
import dlib.geometry.triangle;

import dmech.contact;
import dmech.rigidbody;
import dmech.geometry;
import dmech.mpr;
import dmech.clipping;

// TODO: move projectPoint and unprojectPoint to dlib.geometry.plane
Vector2f projectPoint(
    Vector3f point, 
    Vector3f origin, 
    Vector3f right,
    Vector3f up)
{
    Vector2f res;
    res.x = dot(right, point - origin);
    res.y = dot(up, point - origin);
    return res;
}

Vector3f unprojectPoint(
    Vector2f point, 
    Vector3f origin, 
    Vector3f right,
    Vector3f up)
{
    Vector3f res;
    res = origin + up * point.y + right * point.x;
    return res;
}

/*
 * Contact manifold.
 * Stores information about two bodies' collision
 */
struct ContactManifold
{
    Contact[8] contacts;
    uint numContacts = 0;

    void computeContacts(Contact c)
    {
        // If colliding with a sphere, there's only one contact
        if (c.body1.geometry.type == GeomType.Sphere ||
            c.body2.geometry.type == GeomType.Sphere)
        {
            contacts[0] = c;
            numContacts = 1;
            return;
        }

        if (c.body1.geometry.type == GeomType.Ellipsoid ||
            c.body2.geometry.type == GeomType.Ellipsoid)
        {
            contacts[0] = c;
            numContacts = 1;
            return;
        }

        // Calculate tangent space for contact normal
        Vector3f n = c.normal;
        Vector3f n0 = cross(n, Vector3f(0.0f, 0.0f, 1.0f));
        if (abs(n0.length) < 0.01f)
            n0 = cross(n, Vector3f(1.0f, 0.0f, 0.0f));
        Vector3f n1 = cross(n, n0);
        n0.normalize();
        n1.normalize();
        
        Vector3f right = n0;
        Vector3f up = n1;

        Plane contactPlane;
        contactPlane.fromPointAndNormal(c.point, c.normal);

        // Scan contact features by rotating axis
        Feature f1, f2;
        
        f1.numVertices = 0;
        f2.numVertices = 0;
        
        float eps = 0.05f;
        
        // If colliding with a cylinder, use smaller contact area
        if (c.body1.geometry.type == GeomType.Cylinder ||
            c.body2.geometry.type == GeomType.Cylinder)
        {
            eps = 0.05f;
        }

        if (c.body1.geometry.type == GeomType.Cone ||
            c.body2.geometry.type == GeomType.Cone)
        {
            eps = 0.05f;
        }

        float startAng = PI / 4;
        float stepAng = PI / 2; // 90 degrees

        uint numAxes1 = 4;

        if (c.body1.geometry.type == GeomType.Triangle)
        {
            numAxes1 = 3;
            startAng = 0;
            stepAng = radtodeg(120.0f);
        }

        for(uint i = 0; i < numAxes1; i++)
        {
            float ang = startAng + stepAng * i;

            Vector3f axis = (c.normal + n0 * cos(ang) * eps + n1 * sin(ang) * eps).normalized;
            
            Vector3f p;

            supportTransformed(c.body1.geometry, -axis, p);
            if (contactPlane.distance(p) < 0.0f)
            {
                Vector2f planePoint = projectPoint(p, c.point, right, up);
                f1.vertices[f1.numVertices] = planePoint;
                f1.numVertices++;
            }
        }

        uint numAxes2 = 4;

        if (c.body2.geometry.type == GeomType.Triangle)
        {
            numAxes2 = 3;
            startAng = 0;
            stepAng = radtodeg(120.0f);
        }

        for(uint i = 0; i < numAxes2; i++)
        {
            float ang = startAng + stepAng * i;

            Vector3f axis = (c.normal + n0 * cos(ang) * eps + n1 * sin(ang) * eps).normalized;
            
            Vector3f p;

            supportTransformed(c.body2.geometry, axis, p);
            if (contactPlane.distance(p) > 0.0f)
            {
                Vector2f planePoint = projectPoint(p, c.point, right, up);
                f2.vertices[f2.numVertices] = planePoint;
                f2.numVertices++;
            }
        }

        // Clip features in 2D space: find their overlapping polygon
        Vector2f[8] clippedPoints;
        uint numClippedPoints;
        clip(f1, f2, clippedPoints, numClippedPoints);

        // Transform the resulting points back into 3D space
        // TODO: pesistent contacts
        numContacts = 0;
        for(uint i = 0; i < numClippedPoints; i++)
        {
            Contact newc;
            newc.fact = true;
            newc.body1 = c.body1;
            newc.body2 = c.body2;
            newc.point = unprojectPoint(clippedPoints[i], c.point, right, up);
            newc.normal = c.normal;
            newc.penetration = c.penetration;
            contacts[i] = newc;
            numContacts++;
        }
    }
}
