/*
Copyright (c) 2013 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module dmech.solver;

import std.math;
import std.algorithm;

import dlib.math.utils;
import dlib.math.vector;

import dmech.contact;
import dmech.rigidbody;

void prepareContact(Contact* c, bool warmstarting = false)
{
    RigidBody body1 = c.body1;
    RigidBody body2 = c.body2;
    
    Vector3f r1 = c.point - body1.position;
    Vector3f r2 = c.point - body2.position;
    
    Vector3f relativeVelocity = Vector3f(0.0f, 0.0f, 0.0f);

    relativeVelocity += body1.linearVelocity + cross(body1.angularVelocity, r1);
    relativeVelocity -= body2.linearVelocity + cross(body2.angularVelocity, r2);
    
    c.initialVelocityProjection = dot(relativeVelocity, c.normal);

    if (warmstarting)
    {
        Vector3f impulseVec = c.normal * c.accumulatedImpulse;

        if (body1.dynamic) 
            body1.applyImpulse(+impulseVec, c.point);
        if (body2.dynamic) 
            body2.applyImpulse(-impulseVec, c.point);
    }
}

void solveContact(Contact* c, float dt, bool baumgarte = false, bool warmstarting = false)
{
    RigidBody body1 = c.body1;
    RigidBody body2 = c.body2;
    
    Vector3f r1 = c.point - body1.position;
    Vector3f r2 = c.point - body2.position;
    
    Vector3f relativeVelocity = Vector3f(0.0f, 0.0f, 0.0f);

    relativeVelocity += body1.linearVelocity + cross(body1.angularVelocity, r1);
    relativeVelocity -= body2.linearVelocity + cross(body2.angularVelocity, r2);
    
    float velocityProjection = dot(relativeVelocity, c.normal);
    
    // Check if the bodies are already moving apart
    if (velocityProjection > 0.0f)
        return;
    
    // Jacobian
    Vector3f n1 = c.normal;
    Vector3f w1 = c.normal.cross(r1);
    Vector3f n2 = -c.normal;
    Vector3f w2 = -c.normal.cross(r2);

    float bounce = (body1.bounce + body2.bounce) * 0.5f;
    float damping = 0.9f;
    float C = max(0, -bounce * c.initialVelocityProjection - damping);

    float a = velocityProjection;
    /*
        dot(body1.linearVelocity, n1)
      + dot(cross(body1.angularVelocity, r1), w1)
      + dot(body2.linearVelocity, n2)
      + dot(cross(body2.angularVelocity, r2), w2);
    */
    
    float bias = 0.0f;
    
    if (baumgarte)
    {
        float allowedPenetration = 0.02f;
        float biasFactor = 0.2f; // 0.1 to 0.3
        float inv_dt = 1.0f / dt;
        bias = biasFactor * inv_dt * max(0.0f, c.penetration - allowedPenetration);
    }

    float b = dot(n1, n1 * body1.invMass)
            + dot(w1, w1 * body1.invInertia)
            + dot(n2, n2 * body2.invMass)
            + dot(w2, w2 * body2.invInertia);

    float normalImpulse = (C - a + bias) / b;

    if (warmstarting)
    {
        c.accumulatedImpulse += normalImpulse;
        if (c.accumulatedImpulse < 0.0f)
        {
            normalImpulse += 0.0f - c.accumulatedImpulse;
            c.accumulatedImpulse = 0.0f;
        }
    }
    else
    {
        if (normalImpulse < 0.0f)
            normalImpulse = 0.0f;
    }

    // Friction
    float mu = (body1.friction + body2.friction) * 0.5f;
    Vector3f fVec = Vector3f(0.0f, 0.0f, 0.0f);
/*
    Vector3f fdir1, fdir2;
    if (dot(c.normal, Vector3f(1,0,0)) < 0.5f)
        fdir1 = cross(c.normal, Vector3f(1,0,0)); 
    else
        fdir1 = cross(c.normal, Vector3f(0,0,1));
    fdir2 = cross(fdir1, c.normal);
    fdir1.normalize();
    fdir2.normalize();
*/
    Vector3f t = c.fdir1;
    float num = -dot(relativeVelocity, t);
    float denom = 
        body1.invMass
      + body2.invMass
      + dot(cross(r1, cross(t, r1) * body1.invInertia), t)
      + dot(cross(r2, cross(t, r2) * body2.invInertia), t);
    float jf = num / denom;
    jf = clamp(jf, -normalImpulse * mu, normalImpulse * mu);
    fVec = t * jf;

    t = c.fdir2;
    num = -dot(relativeVelocity, t);
    denom = 
        body1.invMass
      + body2.invMass
      + dot(cross(r1, cross(t, r1) * body1.invInertia), t)
      + dot(cross(r2, cross(t, r2) * body2.invInertia), t);
    jf = num / denom;
    jf = clamp(jf, -normalImpulse * mu, normalImpulse * mu);
    fVec += t * jf;
    
    // Apply impulse
    Vector3f impulseVec = c.normal * normalImpulse;
    impulseVec += fVec;

    if (body1.dynamic) 
        body1.applyImpulse(+impulseVec, c.point);
    if (body2.dynamic) 
        body2.applyImpulse(-impulseVec, c.point);
}

void solvePositionError(Contact* c, float dt)
{
    RigidBody body1 = c.body1;
    RigidBody body2 = c.body2;
    
    Vector3f r1 = c.point - body1.position;
    Vector3f r2 = c.point - body2.position;
       
    Vector3f prv = Vector3f(0.0f, 0.0f, 0.0f);
    prv += body1.pseudoLinearVelocity + cross(body1.pseudoAngularVelocity, r1);
    prv -= body2.pseudoLinearVelocity + cross(body2.pseudoAngularVelocity, r2);
    float pvp = dot(prv, c.normal);
    
    float ERP = 1.0f;
    float pc = c.penetration * ERP;
    
    if (pvp >= pc)
        return;
        
    // Jacobian
    Vector3f n1 = c.normal;
    Vector3f w1 = c.normal.cross(r1);
    Vector3f n2 = -c.normal;
    Vector3f w2 = -c.normal.cross(r2);

    float a = pvp;

    float b = dot(n1, n1 * body1.invMass)
            + dot(w1, w1 * body1.invInertia)
            + dot(n2, n2 * body2.invMass)
            + dot(w2, w2 * body2.invInertia);
    
    float impulse = (pc - a) / b;
    Vector3f impulseVec = c.normal * impulse;
    
    if (body1.dynamic) 
        body1.applyImpulse(+impulseVec, c.point);
    if (body2.dynamic) 
        body2.applyImpulse(-impulseVec, c.point);
}

