/*
Copyright (c) 2013 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module dmech.world;

import std.stdio;

import dlib.math.vector;
import dlib.math.matrix;
import dlib.math.quaternion;
import dlib.geometry.sphere;
import dlib.geometry.triangle;

import dmech.geometry;
import dmech.rigidbody;
import dmech.collision;
import dmech.contact;
import dmech.manifold;
import dmech.hashtable;
import dmech.solver;
import dmech.constraint;
import dmech.bvh;
import dmech.mpr;

class PhysicsWorld
{
    RigidBody[] staticBodies;
    RigidBody[] dynamicBodies;
    Constraint[] constraints;

    Vector3f gravity;

    protected uint maxBodyId = 0;

    //enum MaxCollisions = 1000;
    PairHashTable!(ContactManifold, ulong) manifolds;

    bool broadphase = false;

    BVHTree!RigidBody bvh; 
    
    this(size_t maxCollisions = 1000)
    {
        gravity = Vector3f(0.0f, -9.80665f, 0.0f); // Earth

        manifolds = new PairHashTable!(ContactManifold, ulong)(maxCollisions);
    }

    RigidBody addDynamicBody(Vector3f pos, float mass)
    {
        auto b = new RigidBody();
        b.position = pos;
        b.mass = mass;
        b.invMass = 1.0f / mass;
        b.inertia = matrixf(
            mass, 0, 0,
            0, mass, 0,
            0, 0, mass
        );
        b.invInertia = matrixf(
            0, 0, 0,
            0, 0, 0,
            0, 0, 0
        );
        b.dynamic = true;
        b.id = maxBodyId;
        maxBodyId++;
        dynamicBodies ~= b;
        return b;
    }

    RigidBody addStaticBody(Vector3f pos)
    {
        auto b = new RigidBody();
        b.position = pos;
        b.mass = float.infinity;
        b.invMass = 0.0f;
        b.inertia = matrixf(
            float.infinity, 0, 0,
            0, float.infinity, 0,
            0, 0, float.infinity
        );
        b.invInertia = matrixf(
            0, 0, 0,
            0, 0, 0,
            0, 0, 0
        );
        b.dynamic = false;
        b.id = maxBodyId;
        maxBodyId++;
        staticBodies ~= b;
        return b;
    }

    Constraint addConstraint(Constraint c)
    {
        constraints ~= c;
        return c;
    }

    void buildStaticBVH()
    {
        bvh = new BVHTree!RigidBody(staticBodies, 16);
    }

    void update(float dt)
    {
        if (dynamicBodies.length == 0)
            return;

        foreach(b; dynamicBodies)
        {
            b.updateInertia();
            b.applyForce(gravity * b.mass);
            b.integrateForces(dt);
            b.resetForces();
        }

        if (broadphase)
            findDynamicCollisionsBroadphase();
        else
            findDynamicCollisionsBruteForce();

        if (broadphase)
            findStaticCollisionsBVH();
        else
            findStaticCollisionsBruteForce();

        solveCollisions(dt);
        solveConstraints(dt);

        foreach(b; dynamicBodies)
        {
            b.integrateVelocities(dt);
            b.updateGeometryTransformation();
        }
    }

    void findDynamicCollisionsBruteForce()
    {
        for (int i = 0; i < dynamicBodies.length - 1; i++)   
        for (int j = i + 1; j < dynamicBodies.length; j++)
        {
            checkCollisionPair(dynamicBodies[i], dynamicBodies[j]);
        }
    }

    void findDynamicCollisionsBroadphase()
    {
        for (int i = 0; i < dynamicBodies.length - 1; i++)   
        for (int j = i + 1; j < dynamicBodies.length; j++)
        {
            if (dynamicBodies[i].geometry.boundingBox.intersectsAABB(dynamicBodies[j].geometry.boundingBox))
            {
                checkCollisionPair(dynamicBodies[i], dynamicBodies[j]);
            }
        }
    }

    void findStaticCollisionsBruteForce()
    {
        foreach(b1; dynamicBodies)
        foreach(b2; staticBodies)
        {
            checkCollisionPair(b1, b2);
        }
    }

    void findStaticCollisionsBVH()
    {
        foreach(b1; dynamicBodies)
        {
            auto bsphere = b1.geometry.boundingSphere;
            bvh.root.traverseBySphere(bsphere, (ref RigidBody b2)
            {
                checkCollisionPair(b1, b2);
            });
        }
    }

    void checkCollisionPair(RigidBody body1, RigidBody body2)
    {
        Contact c;
        if (checkCollision(body1, body2, c))
        {
            auto m = manifolds.get(body1.id, body2.id);
            if (m is null)
            {
                ContactManifold m1;
                m1.computeContacts(c);
                manifolds.set(body1.id, body2.id, m1);
            }
            else
            {
                m.computeContacts(c);
            }
        }
        else
        {
            manifolds.remove(body1.id, body2.id);
        }
    }

    void solveCollisions(float dt)
    {
        enum contactIterations = 10;

        foreach(ref m; manifolds)
        foreach(i; 0..m.numContacts)
        {
            auto c = &m.contacts[i];
            prepareContact(c);
        }

        foreach(iteration; 0..contactIterations)
        {
            foreach(ref m; manifolds)
            foreach(i; 0..m.numContacts)
            {
                auto c = &m.contacts[i];
                solveContact(c, dt, true);
            }
        }
    }

    void solveConstraints(float dt)
    {
        enum constraintIterations = 5;
        foreach(c; constraints)
        {
            c.prepare(dt);
            for (int i = 0; i < constraintIterations; i++)
                c.step();
        }
    }
}

