/*
Copyright (c) 2013 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module dmech.world;

import std.stdio;

import dlib.math.vector;
import dlib.math.quaternion;
import dlib.geometry.sphere;
import dlib.geometry.triangle;

import dmech.geometry;
import dmech.rigidbody;
import dmech.collision;
import dmech.contact;
import dmech.manifold;
import dmech.hashtable;
import dmech.solver;
import dmech.constraint;
import dmech.mpr;

class PhysicsWorld
{
    RigidBody[] bodies;
    Constraint[] constraints;

    Vector3f gravity;

    protected uint maxBodyId = 0;

    enum MaxCollisions = 1000;
    PairHashTable!ContactManifold manifolds;
    
    this(Vector3f grav = Vector3f(0.0f, -9.80665f, 0.0f))
    {
        gravity = grav;
        manifolds = new PairHashTable!ContactManifold(MaxCollisions);
    }

    RigidBody addDynamicBody(Vector3f pos, float mass)
    {
        auto b = new RigidBody();
        b.position = pos;
        b.mass = mass;
        b.invMass = 1.0f / mass;
        b.inertiaMoment = b.mass;
        b.invInertiaMoment = 1.0f / b.inertiaMoment;
        b.dynamic = true;
        b.id = maxBodyId;
        maxBodyId++;
        bodies ~= b;
        return b;
    }

    RigidBody addStaticBody(Vector3f pos)
    {
        auto b = new RigidBody();
        b.position = pos;
        b.mass = float.max;
        b.invMass = 0.0f;
        b.inertiaMoment = float.max;
        b.invInertiaMoment = 0.0f;
        b.dynamic = false;
        b.id = maxBodyId;
        maxBodyId++;
        bodies ~= b;
        return b;
    }

    Constraint addConstraint(Constraint c)
    {
        constraints ~= c;
        return c;
    }

    void update(float dt)
    {
        if (bodies.length == 0)
            return;           

        foreach(b; bodies)
        {
            b.applyForce(b.mass * gravity);
            b.integrateForces(dt);
            b.resetForces();
        }

        findCollisions();
        solveCollisions(dt);
        solveConstraints(dt);

        foreach(b; bodies)
        {
            b.integrateVelocities(dt);
            b.updateGeometryTransformation();
        }
    }

    void findCollisions()
    {
        for (int i = 0; i < bodies.length - 1; i++)   
        for (int j = i + 1; j < bodies.length; j++)
        {
            Contact c;
            if (checkCollision(bodies[i], bodies[j], c))
            {
                auto m = manifolds.get(bodies[i].id, bodies[j].id);
                if (m is null)
                {
                    ContactManifold m1;
                    m1.computeContacts(c);
                    manifolds.set(bodies[i].id, bodies[j].id, m1);
                }
                else
                    m.computeContacts(c);
            }
            else
                manifolds.remove(bodies[i].id, bodies[j].id);
        }
    }

    void solveCollisions(float dt)
    {
        foreach(ref entry; manifolds.table)
        {
            if (entry.valid)
            {
                auto m = &entry.value;
                foreach(i; 0..m.numContacts)
                {
                    auto c = &m.contacts[i];
                    prepareContact(c);
                }
            }
        }

        foreach(iteration; 0..60)
        {
            foreach(ref entry; manifolds.table)
            {
                if (entry.valid)
                {
                    auto m = &entry.value;
                    
                    foreach(i; 0..m.numContacts)
                    {
                        auto c = &m.contacts[i];
                        solveContact(c, dt);
                    }
                }
            }
        }
    }

    void solveConstraints(float dt)
    {
        enum constraintIterations = 5;
        foreach(c; constraints)
        {
            c.prepare(dt);
            for (int i = 0; i < constraintIterations; i++)
                c.step();
        }
    }
}

